displayName=Ring Menu
author=mepatrick73
description=Radial ring menu for quickly accessing bank tags and inventory setups
tags=ring,menu,radial,bank,inventory,setups
plugins=com.mepatrick73.ringmenu.RingMenuPlugin
version=1.0.3
build=standard
